[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Oscar Nylander <oscar@hedvig.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.2.2"
aoc-runner-derive = "0.2.2"
fxhash = "0.2.1"
chrono = "0.4.6"
skiplist = "0.2.10"
